### ISSUE TITLE
Adding cash deposit bank information alert

### ISSUE THREAD

**Issue by alfsbs** [bisq-network/payment-methods#1]
For cash deposits in the US, you need to know the bank name before(!) you initiate the the trade. If the buyer has to proceed with trade, has her BtC funds locked, only to find out that the bank to deposit cash to is not in her area, then that situation creates a problem -> trade needs to be cancelled etc…

The only way to see the info (if provided) is to go t “Buy BTC” screen, under “Payment Method” hover over (but do not click) the “i” (info) button

@ManfredKarrer do you think it would be convenient and practical to implement an alert in cash deposits when taking an offer such as the following?

> Please confirm that <bank name> operates in your area

**Comment by alfsbs** [comment]
Perfect, The BIC should be enough.
Yes, we could limit creating buy offers for cash deposits. There are currently none created.

**Comment by memetat** [comment]
"Maybe we need to disable to create buy offers for cash deposit?"
Disabling? I dont think that is necessary,  cash deposit creator/buyer can just list the banks he is able to accept. Easy/Works OK in my country. 
i must agree we need this bank info displayed more prominently, not just a tool tip.
When you click an offer to get more info, the offerer's bank name is not listed, the taker needs that same info from the tooltip to make a decision if he can take it & need more info not less from that screen. i think i was meant to make an issue about that at one stage.


i just noticed alfbs comment agreeing to disable. PLEASE dont disable, its a strong feature to keep! (maybe they WERE created but nobody accepted :)

**Comment by alfsbs** [comment]
I'm closing the issue as it has been included in 0.7.0

https://bisq.community/t/new-version-0-7-0-released/5439
